### ISSUE TITLE
execjs._exceptions.ProgramError: TypeError: 'global' 未定义

### ISSUE THREAD

**Issue by 556isback** [01ly/TTBot#11]
是js文件有问题吗
`
from component.user import TTUser

user = TTUser('50502346296')

followings_100 = user.get_followings(MDB=False, count=100)
`

报错信息
`
Traceback (most recent call last):
  File "D:/miniconda/Scripts/news/TTBot/test.py", line 13, in <module>
    followings_100 = user.get_followings(MDB=False, count=100)
  File "D:\miniconda\Scripts\news\TTBot\deco\user.py", line 78, in wrapper
    params = payload_for_relation(self.id,cursor)
  File "D:\miniconda\Scripts\news\TTBot\util\user.py", line 43, in payload_for_relation
    '_signature': py_to_js(signature_js_path, signature_js_func, (uid, cursor)),
  File "D:\miniconda\Scripts\news\TTBot\util\jstool.py", line 37, in py_to_js
    result = JsContext.call(js_func,*params)
  File "D:\miniconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\miniconda\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\miniconda\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\miniconda\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\miniconda\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\miniconda\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 'global' 未定义

Process finished with exit code 1
`

**Comment by toby2** [comment]
遇到相同的问题

**Comment by yzhaotc** [comment]
安装Nodejs

**Comment by JSY-git** [comment]
安装了还是不行啊，解决了吗

**Comment by yzhaotc** [comment]
我是安装了 Nodejs解决的.
